In [8]:
import numpy as np

In [5]:
%%time
N=10000
list_ = list(range(N))
for i in range(N):
    list_sum=sum(list_)

CPU times: total: 547 ms
Wall time: 548 ms


In [17]:
%%time
arr=np.arange(N)
arr_sum=np.sum(arr)
print(arr)
a2

[   0    1    2 ... 9997 9998 9999]
CPU times: total: 0 ns
Wall time: 1 ms


In [23]:
arr=np.array([0.0,2,4,6,8,10])
print(arr,type(arr))
arr.dtype
arr2=np.array([[[3,2,3],[5,6,2]],[[9,5,2],[4,7,2]]])
arr3=arr[np.newaxis, :]

[ 0.  2.  4.  6.  8. 10.] <class 'numpy.ndarray'>


In [50]:
i=1
j=1
k=2
arr2[i,j,k]
print(arr2[1,0,2], "\n") 
print(arr2[1,:,:], "\n")
print(arr2[1,:,:-1], "\n")
print(arr2[1,:,0:2], "\n")
print(arr2[1,:,::2], "\n")

2 

[[9 5 2]
 [4 7 2]] 

[[9 5]
 [4 7]] 

[[9 5]
 [4 7]] 

[[9 2]
 [4 2]] 



In [61]:
arr2.ndim  # ndim gives the number of dimensions.
print(arr2[0:1,:,::2])
print(arr2[0,:,::2])


[[[3 3]
  [5 2]]]
[[3 3]
 [5 2]]


In [101]:
np.zeros((2,3,4))
np.ones((4,2,3))
print(np.random.rand(2,3,4))  # gives a 3d array with random positive numbers
print(np.random.randn(2,3,4))  #gives a 3d array with random positive and negative numbers

[[[0.84528036 0.57348061 0.33140989 0.95564649]
  [0.455103   0.48504328 0.96129584 0.48726208]
  [0.94219904 0.74424358 0.23534075 0.4696453 ]]

 [[0.99583489 0.36525262 0.77124148 0.32413943]
  [0.23005054 0.90427486 0.2087902  0.09140921]
  [0.15346907 0.85639302 0.53520463 0.71818567]]]
[[[ 1.13935735 -3.55684555 -0.39446939 -0.6646725 ]
  [ 0.32147495  0.76551458  1.87003442  1.11760268]
  [ 0.96421854 -0.02858816  1.62863264 -0.32088182]]

 [[-0.68260824 -2.17624166  0.49808408 -0.96224428]
  [-0.60698904 -1.03327687  0.69350295 -0.40505697]
  [ 0.11914249 -0.86036936 -0.23760701 -1.72017787]]]


In [104]:
np.random.randint(0,100,(3,2,2,3))

array([[[[68,  3, 93],
         [59, 38,  7]],

        [[20, 49,  4],
         [19, 10, 22]]],


       [[[97,  5, 49],
         [43, 50, 89]],

        [[62, 96,  5],
         [ 6,  7,  6]]],


       [[[58, 15, 69],
         [63, 84, 71]],

        [[40, 96, 98],
         [45, 93, 81]]]])

In [109]:
np.linspace(7,70,12)

array([ 7.        , 12.72727273, 18.45454545, 24.18181818, 29.90909091,
       35.63636364, 41.36363636, 47.09090909, 52.81818182, 58.54545455,
       64.27272727, 70.        ])

In [112]:
np.exp(np.random.randint(0,10,(5)))

array([8.10308393e+03, 2.00855369e+01, 1.00000000e+00, 2.98095799e+03,
       1.09663316e+03])

In [122]:
arr=([1,2,3,4,5])
np.amin(arr)  # gives min value
np.amax(arr)  # gives max value
np.mean(arr)
np.median(arr)
np.var(arr)
np.percentile(arr, 90)  # 90th percentile pe kon bheta hai

4.6

In [151]:
%%time
arr=np.random.randint(0,100,(10000))
iqr=np.percentile(arr,75)-np.percentile(arr,25)
print(np.percentile(arr,50))
print(iqr)

48.0
49.0
CPU times: total: 0 ns
Wall time: 2 ms


In [162]:
bins=np.arange(10000)
np.histogram(arr, bins)

(array([105,  93, 105, ...,   0,   0,   0], dtype=int64),
 array([   0,    1,    2, ..., 9997, 9998, 9999]))

In [163]:
import numpy as np
import pandas as pd

In [381]:
arr=np.random.randint(0,10,(4,4))
df = pd.DataFrame(arr)
print(df)
df.index=['R1','R2','R3','R4']
df.columns=['C1','C2','C3','C4']
df
df.describe()['C1'].nunique()

   0  1  2  3
0  6  5  3  7
1  0  7  4  0
2  5  4  5  9
3  6  1  8  0


7

In [183]:
df.loc['R3','C2']  # put the location of the shit
df.iloc[2,1]  # put the og location of the shit

5

In [188]:
type(df.iloc[2:4,1:3])
df.iloc[2:4,1:3]

<class 'pandas.core.frame.DataFrame'>


C2  C3
R3   9   2
R4   9   8

In [421]:
def createShit(nRow, nColumn, maxRand=10):
    arr=np.random.randint(0, maxRand,(nRow,nColumn))
    df=pd.DataFrame(arr)
    index = ['R0']
    column = ['C0']
    for x in np.arange(1,nRow+1):
        row= str(x)+"R"
        index.extend(row)
    print(index)
#         ind.append('R'+ str(x))
    for y in np.arange(1,nColumn+1):
         column.extend('C'+str(y))
    print(column)
#         col.append('C'+ str(y))
    #df.index = index
    #df.column = column
   # return df

In [422]:
createShit(5,7)

['R0', '1', 'R', '2', 'R', '3', 'R', '4', 'R', '5', 'R']
['C0', 'C', '1', 'C', '2', 'C', '3', 'C', '4', 'C', '5', 'C', '6', 'C', '7']


In [391]:
mass = pd.Series([0.33, 4.87, 5.97, 0.642, 1898, 568, 86.8, 102, 0.0146],
                index=['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto'])
diameter = pd.Series([4879, 12104, 12756, 3475, 6792, 142984, 120536, 51118, 49528, 2370],
                    index=['Mercury', 'Venus', 'Earth', 'Moon', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto'])
df = pd.DataFrame({'Mass':mass,'Diameter':diameter})
df['Mass']['Earth']

5.97

In [392]:
df['Pop']=0
df['Pop']['Earth']=8000000000
df['Mass'].unique
df.drop(['Pop'], axis=1, inplace=True)

C:\Users\HJ_Home\AppData\Local\Temp\ipykernel_10008\1492370480.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Pop']['Earth']=8000000000


In [379]:
print(df['Mass'].nunique())

9


In [382]:
import seaborn as sns

In [395]:
df=sns.load_dataset('planets')
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [390]:
df.head()  # takes top 5 by default
df.tail()  # bottom🥵 5 by default

method  number  orbital_period  mass  distance  year
0  Radial Velocity       1           269.3   7.1      77.4  2006

In [398]:
df_ = df.copy()
per_75 = df.distance.quantile(0.75)
per_75
df_.iterrows
# for i,r in df_.iterrows():
#     if r['year'] < 2010:
#         df_.drop(i, inplace=True)
#         continue
    

<bound method DataFrame.iterrows of                method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]>

In [399]:
d = {}
for m in df.method.unique():
    d[m]=df[df.method == m]['method'].count()
print(d)

{'Radial Velocity': 553, 'Imaging': 38, 'Eclipse Timing Variations': 9, 'Transit': 397, 'Astrometry': 2, 'Transit Timing Variations': 4, 'Orbital Brightness Modulation': 3, 'Microlensing': 23, 'Pulsar Timing': 5, 'Pulsation Timing Variations': 1}


In [402]:
# Same SHIT as ABOVE way
df.groupby('method')['method'].count()

method
Astrometry                         2
Eclipse Timing Variations          9
Imaging                           38
Microlensing                      23
Orbital Brightness Modulation      3
Pulsar Timing                      5
Pulsation Timing Variations        1
Radial Velocity                  553
Transit                          397
Transit Timing Variations          4
Name: method, dtype: int64

In [406]:
nifty50 = pd.read_csv('E:/KSI/NIFTY50_2018.csv', index_col=0)
nifty50.head()
# for xlsx file, use pd.read_excel instead.

Open      High       Low     Close
Date                                               
31 Dec 2018  10913.20  10923.55  10853.20  10862.55
28 Dec 2018  10820.95  10893.60  10817.15  10859.90
27 Dec 2018  10817.90  10834.20  10764.45  10779.80
26 Dec 2018  10635.45  10747.50  10534.55  10729.85
24 Dec 2018  10780.90  10782.30  10649.25  10663.50